In [9]:
import tensorflow as tf
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
ion_data=pd.read_csv('./ionosphere_data.csv')

In [11]:
ion_data.head()

feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
0         1         0   0.99539  -0.05889   0.85243   0.02306   0.83398   
1         1         0   1.00000  -0.18829   0.93035  -0.36156  -0.10868   
2         1         0   1.00000  -0.03365   1.00000   0.00485   1.00000   
3         1         0   1.00000  -0.45161   1.00000   1.00000   0.71216   
4         1         0   1.00000  -0.02401   0.94140   0.06531   0.92106   

   feature8  feature9  feature10  ...  feature26  feature27  feature28  \
0  -0.37708   1.00000    0.03760  ...   -0.51171    0.41078   -0.46168   
1  -0.93597   1.00000   -0.04549  ...   -0.26569   -0.20468   -0.18401   
2  -0.12062   0.88965    0.01198  ...   -0.40220    0.58984   -0.22145   
3  -1.00000   0.00000    0.00000  ...    0.90695    0.51613    1.00000   
4  -0.23255   0.77152   -0.16399  ...   -0.65158    0.13290   -0.53206   

   feature29  feature30  feature31  feature32  feature33  feature34  label  
0    0.21266   -0.34090    0.42267   -0.54487    0.18641   -0.45300      g  
1   -0.19040   -0.11593   -0.16626   -0.06288   -0.13738   -0.02447      b  
2    0.43100   -0.17365    0.60436   -0.24180    0.56045   -0.38238      g  
3    1.00000   -0.20099    0.25682    1.00000   -0.32382    1.00000      b  
4    0.02431   -0.62197   -0.05707   -0.59573   -0.04608   -0.65697      g  

[5 rows x 35 columns]

In [12]:
ion_data.dtypes

feature1       int64
feature2       int64
feature3     float64
feature4     float64
feature5     float64
feature6     float64
feature7     float64
feature8     float64
feature9     float64
feature10    float64
feature11    float64
feature12    float64
feature13    float64
feature14    float64
feature15    float64
feature16    float64
feature17    float64
feature18    float64
feature19    float64
feature20    float64
feature21    float64
feature22    float64
feature23    float64
feature24    float64
feature25    float64
feature26    float64
feature27    float64
feature28    float64
feature29    float64
feature30    float64
feature31    float64
feature32    float64
feature33    float64
feature34    float64
label         object
dtype: object

In [13]:
print(ion_data.columns)

Index(['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'feature6',
       'feature7', 'feature8', 'feature9', 'feature10', 'feature11',
       'feature12', 'feature13', 'feature14', 'feature15', 'feature16',
       'feature17', 'feature18', 'feature19', 'feature20', 'feature21',
       'feature22', 'feature23', 'feature24', 'feature25', 'feature26',
       'feature27', 'feature28', 'feature29', 'feature30', 'feature31',
       'feature32', 'feature33', 'feature34', 'label'],
      dtype='object')


In [14]:
ion_data.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [15]:
ion_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   feature1   351 non-null    int64  
 1   feature2   351 non-null    int64  
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21 

In [17]:
ion_data=ion_data.sample(frac=1)


In [18]:
ion_data.drop('feature2',
 axis='columns', inplace=True)

In [19]:
ion_data.head()


feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
180         1   1.00000   1.00000  -1.00000   1.00000  -1.00000  -0.82456   
18          1   0.67065   0.02528   0.66626   0.05031   0.57197   0.18761   
19          0   1.00000  -1.00000   0.00000   0.00000   0.00000   0.00000   
30          1   1.00000  -0.14236   1.00000  -0.16256   1.00000  -0.23656   
254         1   0.32834   0.02520   0.15236   0.21278   0.14919   0.74003   

     feature9  feature10  feature11  ...  feature26  feature27  feature28  \
180   0.34649    0.21053    0.46053  ...   -0.66667    1.00000   -1.00000   
18    0.08776    0.34081    0.63621  ...    0.23724    0.46167    0.24618   
19    1.00000    1.00000    1.00000  ...    1.00000    1.00000    1.00000   
30    1.00000   -0.07514    1.00000  ...   -0.47643    0.98820   -0.49687   
254  -0.25706    0.92324   -0.10312  ...   -0.06295    0.33737   -0.11876   

     feature29  feature30  feature31  feature32  feature33  feature34  label  
180    1.00000   -0.24561    0.35088    0.20175    0.82895    0.07895      b  
18     0.43433    0.25306    0.40663    0.25792    1.00000    0.33036      g  
19     1.00000   -1.00000    1.00000    1.00000    1.00000    1.00000      b  
30     1.00000   -0.75820    1.00000   -0.75761    1.00000   -0.84437      g  
254    0.27657   -0.11409    0.15078    0.13296    0.12197    0.20468      g  

[5 rows x 34 columns]

In [20]:
ion_data['label']=ion_data['label'].map({'g':1,"b":0})


In [21]:
ion_data.head()


feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
180         1   1.00000   1.00000  -1.00000   1.00000  -1.00000  -0.82456   
18          1   0.67065   0.02528   0.66626   0.05031   0.57197   0.18761   
19          0   1.00000  -1.00000   0.00000   0.00000   0.00000   0.00000   
30          1   1.00000  -0.14236   1.00000  -0.16256   1.00000  -0.23656   
254         1   0.32834   0.02520   0.15236   0.21278   0.14919   0.74003   

     feature9  feature10  feature11  ...  feature26  feature27  feature28  \
180   0.34649    0.21053    0.46053  ...   -0.66667    1.00000   -1.00000   
18    0.08776    0.34081    0.63621  ...    0.23724    0.46167    0.24618   
19    1.00000    1.00000    1.00000  ...    1.00000    1.00000    1.00000   
30    1.00000   -0.07514    1.00000  ...   -0.47643    0.98820   -0.49687   
254  -0.25706    0.92324   -0.10312  ...   -0.06295    0.33737   -0.11876   

     feature29  feature30  feature31  feature32  feature33  feature34  label  
180    1.00000   -0.24561    0.35088    0.20175    0.82895    0.07895      0  
18     0.43433    0.25306    0.40663    0.25792    1.00000    0.33036      1  
19     1.00000   -1.00000    1.00000    1.00000    1.00000    1.00000      0  
30     1.00000   -0.75820    1.00000   -0.75761    1.00000   -0.84437      1  
254    0.27657   -0.11409    0.15078    0.13296    0.12197    0.20468      1  

[5 rows x 34 columns]

In [23]:
data=ion_data.iloc[:,:33]
labels=ion_data.iloc[:,33:]


In [24]:
data.head()

feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
180         1   1.00000   1.00000  -1.00000   1.00000  -1.00000  -0.82456   
18          1   0.67065   0.02528   0.66626   0.05031   0.57197   0.18761   
19          0   1.00000  -1.00000   0.00000   0.00000   0.00000   0.00000   
30          1   1.00000  -0.14236   1.00000  -0.16256   1.00000  -0.23656   
254         1   0.32834   0.02520   0.15236   0.21278   0.14919   0.74003   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
180   0.34649    0.21053    0.46053  ...    1.00000   -0.66667    1.00000   
18    0.08776    0.34081    0.63621  ...    0.48838    0.23724    0.46167   
19    1.00000    1.00000    1.00000  ...   -1.00000    1.00000    1.00000   
30    1.00000   -0.07514    1.00000  ...    1.00000   -0.47643    0.98820   
254  -0.25706    0.92324   -0.10312  ...    0.27942   -0.06295    0.33737   

     feature28  feature29  feature30  feature31  feature32  feature33  \
180   -1.00000    1.00000   -0.24561    0.35088    0.20175    0.82895   
18     0.24618    0.43433    0.25306    0.40663    0.25792    1.00000   
19     1.00000    1.00000   -1.00000    1.00000    1.00000    1.00000   
30    -0.49687    1.00000   -0.75820    1.00000   -0.75761    1.00000   
254   -0.11876    0.27657   -0.11409    0.15078    0.13296    0.12197   

     feature34  
180    0.07895  
18     0.33036  
19     1.00000  
30    -0.84437  
254    0.20468  

[5 rows x 33 columns]

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data,labels, test_size=0.40)

In [27]:
x_train.shape


(210, 33)

In [28]:
x_test.shape

(141, 33)

In [29]:
y_train.shape


(210, 1)

In [30]:
y_test.shape


(141, 1)

In [31]:
mean=x_train.mean()
std=x_train.std()
x_train -= mean
x_train /=std
x_test -= mean
x_test /=std


In [32]:
x_test.head()

feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
337  0.358354  0.525759  0.857823  0.114446  1.431125 -0.468567  1.642758   
336  0.358354  0.491890  0.745606  0.169192  1.248750 -0.287702  1.471724   
241  0.358354  0.485673 -0.087506  0.584452 -0.278088  0.786723 -0.252916   
347  0.358354  0.623149 -0.059219  0.682618 -0.283728  0.773571 -0.254832   
2    0.358354  0.718990 -0.143105  0.770757 -0.213602  0.902955 -0.453098   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
337 -1.422043   1.621612  -1.912293  ...   0.167778  -1.409132   0.405111   
336 -0.974429   1.555427  -1.545985  ...  -0.539143  -1.172909  -0.522176   
241  0.723249  -0.536278   0.568028  ...   0.906730  -0.213763   0.677836   
347  0.829218  -0.252723   0.825659  ...   0.977637   0.184420   0.779617   
2    0.719140  -0.260779   0.403635  ...   0.378914  -0.608988   0.113464   

     feature28  feature29  feature30  feature31  feature32  feature33  \
337  -0.805601   0.920129  -0.307339   0.960958   0.449916   0.729067   
336  -0.901026   0.172739  -0.776400   0.364166  -0.355222   0.446611   
241  -0.099104   0.835751  -0.195809   0.970366  -0.297576   1.148565   
347   0.248258   0.982526   0.204238   1.070327   0.058040   1.143339   
2    -0.225975   0.148257  -0.281468   0.474492  -0.405912   0.441840   

     feature34  
337   1.221842  
336   0.084194  
241  -0.345466  
347   0.125498  
2    -0.813632  

[5 rows x 33 columns]

In [33]:
x_train.head(3)


feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
82  0.358354  0.567531  0.104495  0.636801  0.131039  0.699908  0.263962   
15  0.358354 -0.243302 -2.152253  0.770757  0.359626 -1.138160 -2.172205   
92  0.358354  0.147710 -0.617908  0.118416 -0.129157 -0.177207  0.530670   

    feature9  feature10  feature11  ...  feature25  feature26  feature27  \
82  0.624149   0.410525   0.506655  ...  -0.168712   1.611395  -0.662262   
15  0.935090  -2.258914  -0.125913  ...  -0.815247   1.918409  -0.257474   
92  0.254402   0.076127  -0.012156  ...  -0.045527  -0.073842  -0.061166   

    feature28  feature29  feature30  feature31  feature32  feature33  \
82   1.456352  -0.408477   1.400192  -0.547818   1.539670  -0.747212   
15   0.626243  -0.570034   0.048861   1.175462   0.504276  -0.667576   
92   0.087278   0.235719  -0.035752   0.543802  -0.425838   0.330790   

    feature34  
82   1.542327  
15   0.022467  
92   0.345707  

[3 rows x 33 columns]

In [34]:
x_test.head(3)

feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
337  0.358354  0.525759  0.857823  0.114446  1.431125 -0.468567  1.642758   
336  0.358354  0.491890  0.745606  0.169192  1.248750 -0.287702  1.471724   
241  0.358354  0.485673 -0.087506  0.584452 -0.278088  0.786723 -0.252916   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
337 -1.422043   1.621612  -1.912293  ...   0.167778  -1.409132   0.405111   
336 -0.974429   1.555427  -1.545985  ...  -0.539143  -1.172909  -0.522176   
241  0.723249  -0.536278   0.568028  ...   0.906730  -0.213763   0.677836   

     feature28  feature29  feature30  feature31  feature32  feature33  \
337  -0.805601   0.920129  -0.307339   0.960958   0.449916   0.729067   
336  -0.901026   0.172739  -0.776400   0.364166  -0.355222   0.446611   
241  -0.099104   0.835751  -0.195809   0.970366  -0.297576   1.148565   

     feature34  
337   1.221842  
336   0.084194  
241  -0.345466  

[3 rows x 33 columns]

In [35]:
train=x_train

In [36]:
test=x_test


In [37]:
train.head()


feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
82   0.358354  0.567531  0.104495  0.636801  0.131039  0.699908  0.263962   
15   0.358354 -0.243302 -2.152253  0.770757  0.359626 -1.138160 -2.172205   
92   0.358354  0.147710 -0.617908  0.118416 -0.129157 -0.177207  0.530670   
179  0.358354  0.718990 -0.249912  0.770757 -0.471787  0.888088 -0.799899   
327  0.358354  0.718990  2.148337 -0.387472 -0.089591 -0.812571  1.595156   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
82   0.624149   0.410525   0.506655  ...  -0.168712   1.611395  -0.662262   
15   0.935090  -2.258914  -0.125913  ...  -0.815247   1.918409  -0.257474   
92   0.254402   0.076127  -0.012156  ...  -0.045527  -0.073842  -0.061166   
179  0.935090  -0.937493   0.828398  ...   0.532754  -1.678976  -0.083790   
327 -1.561711   1.563602  -1.480757  ...   0.642150  -0.718323   0.624333   

     feature28  feature29  feature30  feature31  feature32  feature33  \
82    1.456352  -0.408477   1.400192  -0.547818   1.539670  -0.747212   
15    0.626243  -0.570034   0.048861   1.175462   0.504276  -0.667576   
92    0.087278   0.235719  -0.035752   0.543802  -0.425838   0.330790   
179  -1.338837   0.062279  -1.547008  -0.168985  -1.648484  -0.089144   
327   0.042307   1.096536   1.951127   0.088856   0.063440  -0.316055   

     feature34  
82    1.542327  
15    0.022467  
92    0.345707  
179  -1.937155  
327   1.767128  

[5 rows x 33 columns]

In [38]:
train_label=np.asarray(y_train)
test_label=np.asarray(y_test)

In [39]:
# now we have the following
#train
#test
#train_label
#test_label


In [40]:
train.shape


(210, 33)

In [41]:
from tensorflow.keras import models
from tensorflow.keras import layers
mymodel=models.Sequential()
mymodel.add(layers.Dense(16, activation='relu', input_shape=(train.shape[1],)))
mymodel.add(layers.Dense(12, activation='relu'))
mymodel.add(layers.Dense(1, activation='sigmoid'))


In [42]:
mymodel.compile(optimizer='rmsprop',
 loss='binary_crossentropy',
 metrics=['accuracy'])


In [43]:
mymodel.fit(train,train_label, epochs=100,batch_size=1)


Epoch 1/100
210/210 [==============================] - 0s 2ms/step - loss: 0.5532 - accuracy: 0.7095
Epoch 2/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4128 - accuracy: 0.8381
Epoch 3/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8810
Epoch 4/100
210/210 [==============================] - 0s 2ms/step - loss: 0.2799 - accuracy: 0.9048
Epoch 5/100
210/210 [==============================] - 0s 2ms/step - loss: 0.2419 - accuracy: 0.9143
Epoch 6/100
210/210 [==============================] - 0s 2ms/step - loss: 0.2199 - accuracy: 0.9095
Epoch 7/100
210/210 [==============================] - 0s 1ms/step - loss: 0.2087 - accuracy: 0.9190
Epoch 8/100
210/210 [==============================] - 0s 1ms/step - loss: 0.1954 - accuracy: 0.9143
Epoch 9/100
210/210 [==============================] - 0s 1ms/step - loss: 0.1822 - accuracy: 0.9238
Epoch 10/100
210/210 [==============================] - 0s 1ms/step - loss: 0.1710 - accura

210/210 [==============================] - 0s 1ms/step - loss: 0.0266 - accuracy: 0.9952
Epoch 82/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0222 - accuracy: 0.9952
Epoch 83/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0232 - accuracy: 0.9952
Epoch 84/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0206 - accuracy: 0.9952
Epoch 85/100
210/210 [==============================] - 0s 2ms/step - loss: 0.0240 - accuracy: 0.9952
Epoch 86/100
210/210 [==============================] - 0s 2ms/step - loss: 0.0198 - accuracy: 0.9952
Epoch 87/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0211 - accuracy: 0.9952
Epoch 88/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0298 - accuracy: 0.9952
Epoch 89/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0239 - accuracy: 0.9952
Epoch 90/100
210/210 [==============================] - 0s 1ms/step - loss: 0.0274 - accuracy: 

In [44]:
results = mymodel.evaluate(test, test_label)

5/5 [==============================] - 0s 5ms/step - loss: 0.9449 - accuracy: 0.9149


In [45]:
pred=mymodel.predict(test)
pred[0:10]


array([[1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.9999237e-01],
       [1.0000000e+00],
       [1.2562101e-16],
       [4.3556899e-02],
       [9.9999690e-01],
       [1.0000000e+00]], dtype=float32)

In [46]:
train_label[0:10]


array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]], dtype=int64)

In [48]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import regularizers
mymodel=models.Sequential()
mymodel.add(layers.Dense(16,kernel_regularizer=regularizers.l2(0.001),
 activation='relu', input_shape=(train.shape[1],)))
mymodel.add(layers.Dense(12,kernel_regularizer=regularizers.l2(0.001),
 activation='relu'))
mymodel.add(layers.Dense(1, activation='sigmoid'))


In [49]:
mymodel.compile(optimizer='rmsprop',
 loss='binary_crossentropy',
 metrics=['accuracy'])


In [50]:
mymodel.fit(train,train_label, epochs=100,batch_size=1, verbose=0)

In [51]:
results = mymodel.evaluate(test, test_label)
results


5/5 [==============================] - 0s 2ms/step - loss: 0.3056 - accuracy: 0.9291


[0.3056017756462097, 0.9290780425071716]

In [52]:
pred=mymodel.predict(test)
pred[0:10]


array([[0.9993062 ],
       [0.9995572 ],
       [0.9992296 ],
       [0.9994552 ],
       [0.9939897 ],
       [0.9990884 ],
       [0.00355357],
       [0.22520578],
       [0.99940795],
       [0.99965215]], dtype=float32)

In [53]:
train_label[0:10]

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]], dtype=int64)